In [ ]:
import numpy as np
a= np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

print('\n')
b= np.zeros((3,3))
print(b)

print('\n')
c= np.ones((4,4))
print(c)

print('\n')
d=np.linspace(1,0,10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[1.         0.88888889 0.77777778 0.66666667 0.55555556 0.44444444
 0.33333333 0.22222222 0.11111111 0.        ]


In [ ]:
a=np.array([[1,2],
            [3,4]])
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)

(2, 2)
int64
2
4


In [ ]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
b=(a[1:2,1:2])
print(b)
print('\n')
print(a[:,2])
print('\n')
print(a[0:2,])
print('\n')
c=a[a>50]
print(c)

[[50]]


[30 60 90]


[[10 20 30]
 [40 50 60]]


[60 70 80 90]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a*b)
print(np.dot(a,b))
print(np.mean(b))
print(np.std(b))

[5 7 9]
[ 4 10 18]
32
5.0
0.816496580927726


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=a**2+np.sin(b)
d=np.sqrt(np.abs(a-b)+1)
print(c/d)




[0.12159875 1.52053786 4.36029225]


In [ ]:
import numpy as np
arr = np.random.randint(-50, 151, size=100)
arr_reshaped = arr.reshape((10, 10))
arr_reshaped[arr_reshaped < 0] = 0
arr_min = arr_reshaped.min()
arr_max = arr_reshaped.max()
normalized = (arr_reshaped - arr_min) / (arr_max - arr_min)
row_means = normalized.mean(axis=1)
print("Original reshaped array (negatives replaced):\n", arr_reshaped)
print("\nNormalized array:\n", normalized)
print("\nRow-wise means:\n", row_means)

Original reshaped array (negatives replaced):
 [[ 12 103  67   0   0  76 124  77  18  36]
 [  0 137  15   0   0 127 116  80   0  30]
 [  0   0 141  73  49 116 148  95  69   0]
 [ 24 137   0 146 139  43  92 132  44 119]
 [149  90  16 121   0  15  21  34  56   4]
 [ 63 115   0   0 128 108  48  49  17  72]
 [ 81   0 115 115  20   0   5  17   0  32]
 [  0  55   0  98  83  91 112  73  33   0]
 [  0  78   4  76  82  53  43   0 105  38]
 [ 56 147  24  29   0 150   0  36  16  56]]

Normalized array:
 [[0.08       0.68666667 0.44666667 0.         0.         0.50666667
  0.82666667 0.51333333 0.12       0.24      ]
 [0.         0.91333333 0.1        0.         0.         0.84666667
  0.77333333 0.53333333 0.         0.2       ]
 [0.         0.         0.94       0.48666667 0.32666667 0.77333333
  0.98666667 0.63333333 0.46       0.        ]
 [0.16       0.91333333 0.         0.97333333 0.92666667 0.28666667
  0.61333333 0.88       0.29333333 0.79333333]
 [0.99333333 0.6        0.10666667 0.80666

In [ ]:
arr = np.arange(1, 13)
c=np.reshape(arr,(3,4))
print(c)
d=np.std(c[0:1,0:])+np.std(c[1:2,0:])+np.std(c[2:,0:])
print(d)
e=np.std(c[0:,0:1])+np.std(c[0:,1:2])+np.std(c[0:,2:])
print(e)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3.3541019662496847
9.836010581021643


In [ ]:
import pandas as py
s=[10, 20, 30, 40, 50]
d=py.Series(s)
print(d)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Lahore", "Karachi", "Lahore"]
}
df = pd.DataFrame(data)

print(df.head())
print(df.tail())
print(df.shape)
print(df.dtypes)
print(df["Name"])
print(df[df["Name"] == "Bob"])
print(df.iloc[1, 2])
print(df[df["Age"] > 28])

df["Score"] = [85, 90, 95]
print(df)

df.loc[df["Name"] == "Charlie", "City"] = "Multan"
print(df)

df.drop("Score", axis=1, inplace=True)
print(df)

print(df["Age"].mean())
print(df["City"].nunique())
print(df.describe())


      Name  Age     City
0    Alice   25   Lahore
1      Bob   30  Karachi
2  Charlie   35   Lahore
      Name  Age     City
0    Alice   25   Lahore
1      Bob   30  Karachi
2  Charlie   35   Lahore
(3, 3)
Name    object
Age      int64
City    object
dtype: object
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
  Name  Age     City
1  Bob   30  Karachi
Karachi
      Name  Age     City
1      Bob   30  Karachi
2  Charlie   35   Lahore
      Name  Age     City  Score
0    Alice   25   Lahore     85
1      Bob   30  Karachi     90
2  Charlie   35   Lahore     95
      Name  Age     City  Score
0    Alice   25   Lahore     85
1      Bob   30  Karachi     90
2  Charlie   35   Multan     95
      Name  Age     City
0    Alice   25   Lahore
1      Bob   30  Karachi
2  Charlie   35   Multan
30.0
3
        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("diabetes.csv")

print(df.shape)
print(df.columns)
print(df.head())
print(df.info())
print(df.describe())

plt.figure()
plt.scatter(df["Glucose"], df["BMI"], c=df["Outcome"])
plt.xlabel("Glucose")
plt.ylabel("BMI")
plt.title("Glucose vs BMI (colored by Outcome)")
plt.show()

plt.figure()
plt.scatter(df["Age"], df["Insulin"], c=df["Outcome"])
plt.xlabel("Age")
plt.ylabel("Insulin")
plt.title("Age vs Insulin (colored by Outcome)")
plt.show()

plt.figure()
plt.scatter(df["BloodPressure"], df["SkinThickness"], c=df["Outcome"])
plt.xlabel("BloodPressure")
plt.ylabel("SkinThickness")
plt.title("BloodPressure vs SkinThickness (colored by Outcome)")
plt.show()

plt.figure()
df.boxplot(column="Glucose", by="Outcome")
plt.show()

plt.figure()
df.boxplot(column="BMI", by="Outcome")
plt.show()

plt.figure()
df.boxplot(column="Insulin", by="Outcome")
plt.show()

plt.figure()
df.boxplot(column="Age", by="Outcome")
plt.show()

df.hist(figsize=(10, 8))
plt.show()

plt.figure(figsize=(8, 6))
plt.imshow(df.corr(), cmap="viridis")
plt.colorbar()
plt.xticks(range(len(df.columns)), df.columns, rotation=90)
plt.yticks(range(len(df.columns)), df.columns)
plt.title("Correlation Matrix")
plt.show()
